global:
  scrape_interval: 15s
  evaluation_interval: 10s

scrape_configs:
  - job_name: tplink
    metrics_path: /snmp
    params: 
      target: ['192.168.0.1']
    static_configs:
      - targets: ['tplinkex:9116']
